drop table if exists movements;
drop table if exists accounts;
drop table if exists clients;

create table clients (
    id bigint generated by default as identity primary key,
    name varchar(120) not null,
    gender varchar(30),
    age integer,
    identification varchar(40) not null unique,
    address varchar(180),
    phone varchar(40),
    password varchar(120),
    status boolean not null
);

create table accounts (
    id bigint generated by default as identity primary key,
    number varchar(40) not null unique,
    type varchar(40) not null,
    initial_balance decimal(19, 2) not null,
    current_balance decimal(19, 2) not null,
    status boolean not null,
    client_id bigint not null,
    constraint fk_accounts_clients foreign key (client_id) references clients(id)
);

create table movements (
    id bigint generated by default as identity primary key,
    date date not null,
    type varchar(40) not null,
    movement_value decimal(19, 2) not null,
    balance decimal(19, 2) not null,
    account_id bigint not null,
    constraint fk_movements_accounts foreign key (account_id) references accounts(id)
);

insert into clients (name, gender, age, identification, address, phone, password, status)
values
    ('Jose Lema', 'Masculino', 30, '1234567890', 'Otavalo sn y principal', '098254785', '1234', true),
    ('Marianela Montalvo', 'Femenino', 28, '0955555555', 'Amazonas y NNUU', '097548965', '5678', true),
    ('Juan Osorio', 'Masculino', 35, '1717171717', '13 junio y Equinoccial', '098874587', '1245', true);

insert into accounts (number, type, initial_balance, current_balance, status, client_id)
values
    ('478758', 'Ahorro', 2000.00, 1425.00, true, 1),
    ('225487', 'Corriente', 100.00, 700.00, true, 2),
    ('495878', 'Ahorros', 0.00, 150.00, true, 3),
    ('496825', 'Ahorros', 540.00, 0.00, true, 2),
    ('585545', 'Corriente', 1000.00, 1000.00, true, 1);

insert into movements (date, type, movement_value, balance, account_id)
values
    ('2022-02-10', 'Retiro', -575.00, 1425.00, 1),
    ('2022-02-10', 'Deposito', 600.00, 700.00, 2),
    ('2022-02-10', 'Deposito', 150.00, 150.00, 3),
    ('2022-02-08', 'Retiro', -540.00, 0.00, 4);
